
<?php

$Smartphone = ['Samsung Galaxy S22', 'Samsung Galaxy S22+', 'Samsung Galaxy A03', 'Samsung Galaxy Xcover 5'];
$Smartphone = array('Samsung Galaxy S22', 'Samsung Galaxy S22+', 'Samsung Galaxy A03', 'Samsung Galaxy Xcover 5');

  
 echo "<table border='2'>";
 echo "<tr>";
 echo "<th>Daftar Smartphone Samsung </th>";
 
 echo "</tr>";

   echo "<tr>";
   echo "<td>$Smartphone[0]</td>";
   echo "</tr>";
   echo "<tr>";
   echo "<td>$Smartphone[1]</td>";
   echo "</tr>";
   echo "<tr>";
   echo "<td>$Smartphone[2]</td>";
   echo "</tr>";
   echo "<tr>";
   echo "<td>$Smartphone[3]</td>";
   echo "</tr>";
 
 echo "</table>";
  
 ?>