
<?php

$Smartphone = array("A"=>"Samsung Galaxy S22", "B"=>"Samsung Galaxy S22+", "C"=>"Samsung Galaxy A03", "D"=>"Samsung Galaxy Xcover 5");

 echo "<table border='2'>";
 echo "<tr>";
 echo "<th style='background-color: red' width='300px' height = '50px'><font size='5'>Daftar Smartphone Samsung </font></th>";
 
 echo "</tr>";

   echo "<tr>";
   echo "<td>". $Smartphone['A'] . "</td>";
   echo "</tr>";
   echo "<tr>";
   echo "<td>". $Smartphone['B'] ."</td>";
   echo "</tr>";
   echo "<tr>";
   echo "<td>". $Smartphone['C'] ."</td>";
   echo "</tr>";
   echo "<tr>";
   echo "<td>". $Smartphone['D'] ."</td>";
   echo "</tr>";
 
 echo "</table>";
  
 ?>

